services:
  tracker-http:
    image: clickonetwo/adobe_usage_tracker:v1.0.0
    restart: unless-stopped
    ports:
      - "5000:80"
      - "5000:80/udp"
    volumes:
      - ./Caddyfile.http:/etc/caddy/Caddyfile
      - caddy-tracker-data:/data
      - caddy-tracker-config:/config
    dns:
      - 8.8.8.8
      - 8.8.4.4
volumes:
  caddy-tracker-data:
    external: true
  caddy-tracker-config:
    external: true
