apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: caddy-tracker-config
  name: caddy-tracker-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
