apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.clickonetwo.service: tracker
  name: tracker-config-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
