apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.clickonetwo.service: tracker
  name: tracker
spec:
  selector:
    matchLabels:
      io.clickonetwo.service: tracker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.clickonetwo.service: tracker
    spec:
      containers:
        - image: clickonetwo/adobe_usage_tracker:v1.1.0
          name: tracker
          ports:
            - containerPort: 443
              hostPort: 443
              protocol: TCP
            - containerPort: 443
              hostPort: 443
              protocol: UDP
          volumeMounts:
            - mountPath: /etc/caddy/Caddyfile
              name: tracker-caddyfile
              subPath: Caddyfile
            - mountPath: /etc/caddy/lcs-ulecs.pem.cert
              name: tracker-ulecs-cert
              subPath: lcs-ulecs.pem.cert
            - mountPath: /etc/caddy/lcs-ulecs.pem.key
              name: tracker-ulecs-key
              subPath: lcs-ulecs.pem.key
            - mountPath: /data
              name: tracker-data-volume
            - mountPath: /config
              name: tracker-config-volume
      restartPolicy: Always
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
      volumes:
        - configMap:
            items:
              - key: Caddyfile
                path: Caddyfile
            name: tracker-caddyfile
          name: tracker-caddyfile
        - configMap:
            items:
              - key: lcs-ulecs.pem.cert
                path: lcs-ulecs.pem.cert
            name: tracker-ulecs-cert
          name: tracker-ulecs-cert
        - configMap:
            items:
              - key: lcs-ulecs.pem.key
                path: lcs-ulecs.pem.key
            name: tracker-ulecs-key
          name: tracker-ulecs-key
        - name: tracker-data-volume
          persistentVolumeClaim:
            claimName: tracker-data-volume
        - name: tracker-config-volume
          persistentVolumeClaim:
            claimName: tracker-config-volume
